import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next-cinema",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <nav className="bg-slate-900 text-white">
          <ul className="flex gap-x-8 p-8">
            <li><Link href="/persons">Person Form</Link></li>
            <li><Link href="/movies">Movie Form</Link></li>
            <li><Link href="/roles">Role Form</Link></li>
            <li><Link href="/genres">Genre Form</Link></li>
            <li><Link href="/persons/list">Persons List</Link></li>
            <li><Link href="/movies/list">Movies List</Link></li>
            <li><Link href="/roles/list">Roles List</Link></li>
            <li><Link href="/genres/list">Genres List</Link></li>
          </ul>
        </nav>

        <main className="px-6 py-6">
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
